FROM ruby:2.6.5-alpine3.10

RUN apk add --update --no-cache build-base tzdata

WORKDIR /app
COPY . /app
RUN gem update --system
RUN gem install bundler -v '2.0.2'
RUN bundle install --path vendor/bundle
CMD ./bin/bundle exec puma
